### ISSUE TITLE
Mac installer doesn't open

### ISSUE THREAD

**Issue by bcometa** [vexorian/dizquetv#1]
0.0.60 Mac installer doesn't open. It may just be missing and extensions or I'm trying to install it incorrectly. I tried renaming with .pkg and doesn't appear to be a pkg file.

**Comment by andrew-snape** [comment]
open up terminal
chmod +x dizquetv-macos-x64

and then run the application, should be fine after that.

**Comment by vexorian** [comment]
There's many reports of people running the os/x installer correctly, so I think it was just a mistake of not making it an executable file.
