### ISSUE TITLE
Feature Request: Refresh all channels (remove and add/import all content)

### ISSUE THREAD

**Issue by RandomGithubUsername** [vexorian/dizquetv#105]
When we add or remove content (to Plex), currently we need to edit the channel (in dizquetv) and manually re-import so that new movies are pulled in or deleted movies/content is no longer in the guide. It becomes very tedious if we have many channels and considering we all constantly keep adding new content, I feel this will be beneficial to everyone. Please consider adding this feature.

**Comment by MoRBiD-MaNGLeR** [comment]
@vexorian This is a duplicate of #10, right?  #10 has a second enhancement in it for easier adding of icons to channels.  How shall we proceed with #10 and #105?

**Comment by vexorian** [comment]
This is indeed a duplicate of #10

Regarding #10 second feature request, it was added in a comment, so it doesn't count.
