### ISSUE TITLE
Adding custom group-title, to allow m3u organisation 

### ISSUE THREAD

**Issue by deanochips** [vexorian/dizquetv#106]
would be great if we could add custom group-title, to allow m3u organisation rather than everything in the one group

**Comment by vexorian** [comment]
I need some help understanding how are groups normally used in "normal" m3us.

**Comment by deanochips** [comment]
its really simple

#EXTINF:0 tvg-id="1" tvg-chno="1" tvg-name="Black Books" tvg-logo="http://192.168.1.16:8000/images/dizquetv.png" group-title="dizqueTV",theshowname

just replace "dizqueTV" with whatever the group you want in "group-title"....thats it

**Comment by vexorian** [comment]
But I don't know what ius it suppose to do.

**Comment by deanochips** [comment]
oh i see

it allows you to create groups of channels......for example Entertainment, Movies, Documentary

here is a screenshot if it helps
https://lh3.googleusercontent.com/Mj1Ilk5cDaQr64UMW2OrElHk2cuwhmcsNFkbmoJUGvnsQb4MXXZStaXhOGUsuOoan_Y=w720-h310-rw

**Comment by MoRBiD-MaNGLeR** [comment]
@deanochips Just curious... what app was that a screenshot of?

**Comment by deanochips** [comment]
Tivimate, in my opinion the best iptv player
https://play.google.com/store/apps/details?id=ar.tvplayer.tv&hl=en_GB

i can't be doing with plex's slow channel changing, for iptv its far superior.
