### ISSUE TITLE
Add url-tvg and x-tvg-url fields to m3u

### ISSUE THREAD

**Issue by vexorian** [vexorian/dizquetv#110]
I was setting up a new Android TV box and realized that when setting up xteve in TiViMate, I only needed to input the m3u address, it didn't have to ask me for the xmltv address.

So it turns out that xteve adds two fields to the m3u that seem to make finding the xmltv automatic in some iptv clients. Would be nice to have those fields in dizquetv's xmltv to wield this power.

```
#EXTM3U url-tvg="http://192.168.0.10:35500/xmltv/xteve.xml" x-tvg-url="http://192.168.0.10:35500/xmltv/xteve.xml"
```

**Comment by MoRBiD-MaNGLeR** [comment]
@vexorian Is this going to get pushed to 0.0.70 instead?  I didn't see this in the changelog for 0.0.69, nor do I see this in my M3U when using 0.0.69.

**Comment by vexorian** [comment]
Seems small enough to be allowed in 1.0.2

**Comment by MoRBiD-MaNGLeR** [comment]
Isn't 1.0.2 only for bugfixes?  This reads like an enhancement to me.

**Comment by vexorian** [comment]
The spirit of the rule is to avoid features that could break the release or features that would break compatibility with the api library or features that require new documentation. This is neither of them.
