### ISSUE TITLE
dizqueTV Guide: Make content-mask duration configurable, plus fix content-mask

### ISSUE THREAD

**Issue by MoRBiD-MaNGLeR** [vexorian/dizquetv#118]
psybertech  09/13/2020
.... I just would like to guide to show what is playing, well, within reason... not 15 seconds at a time, but say 2 minutes? even if the guide can't handle it in grid view is fine, but when you open up the info for what is playing, it would be great to see what is actually on, rather than just some random title

MoRBiD MaNGLeR  Today at 11:10 AM
psybertech, vexorian: I'd like to see this be configurable.  Currently in my schedule, I have an ~11-minute cartoon showing as a ~50-minute cartoon because the 10 cartoons that follow it are 3-4 minutes long each.  [See screenshots at the end.]

vexorian  Today at 11:46 AM
MoRBiD MaNGLeR: I'll make it configurable, but I think this is a bug. The correct way it should render in my opinion would be as a Toy Story Toons episode followed by 40 minutes of "Toy Story" Channel name and icon.

MoRBiD MaNGLeR  Today at 11:53 AM
Like psybertech was mentioning, I'd rather see the sliver scheduling than guide filler... so vexorian, thank you for working to make it configurable.  If there's a bug to fix, I guess that's two things on which to work.

![image](https://user-images.githubusercontent.com/34169521/93253237-770a6800-f74b-11ea-9d52-3563acdcfc52.png)

![image](https://user-images.githubusercontent.com/34169521/93253263-7e317600-f74b-11ea-9a20-5f2281cd9d33.png)

**Comment by vexorian** [comment]
The bug is fixed. So let's leave the issue as a way to track the enhancement.

**Comment by vexorian** [comment]
This is implemented in dev/1.2.x
