### ISSUE TITLE
dizqueTV Guide:  Allow configurable name (by channel) of big block of consecutive short Flex periods

### ISSUE THREAD

**Issue by MoRBiD-MaNGLeR** [vexorian/dizquetv#124]
I see this bugfix in action (from 1.0.1):
** Long (> 30m) blocks of consecutive short Flex periods will render as a big block with the channel name as opposed of getting merged with the previous show. Do remember that short (< 5m) videos are treated the same as Flex by the TV guide.

The channel name in the guide didn't jump out at me at first.  Previously, it used to be 50 minutes of the show prior.  It only differs from what follows it because it doesn't have a Year.  It looks like the channel-name block has a period for the Year:

![image](https://user-images.githubusercontent.com/34169521/93582443-56aef900-f957-11ea-876e-5ad61df015cd.png)

Please introduce this enhancement:
Allow the user, by channel, to specify what the block should be called.

Toy Story is not descriptive enough for me in this case.  I'd rather it be called "Forky Asks a Question".  That would be perfect.

**Comment by vexorian** [comment]
This has been added to dev/1.2.x
