### ISSUE TITLE
If dizquetv is behind https reverse proxy, it uses https to connect to plex instead of http

### ISSUE THREAD

**Issue by quekky** [vexorian/dizquetv#125]
I have dizquetv behind reverse proxy (https://dizquetv.mydomain.com)

It seems that even though on the setting page, plex url is set to http, dizquetv still use https to connect to it instead of http. This cause the plex api to fail as plex returns an invalid cert

![image](https://user-images.githubusercontent.com/3648303/93610406-99c4a700-f9ff-11ea-87a6-92dce0790ff1.png)
![image](https://user-images.githubusercontent.com/3648303/93610475-b234c180-f9ff-11ea-89bc-1e9ae7ab1a51.png)
(In my example, dizquetv is hosted somewhere else, and my local hosts file points to the correct plex IP address. plex is on the same server as dizquetv)

**Comment by vexorian** [comment]
I tried to reproduce this. Changed my server uir from https://xxx to http:// and checked the network tab, it was attempting to connect to http:// , so it seems I couldn't reproduce the issue.

By any chance does your browser have a "https everywhere" plugin or something like that?

**Comment by quekky** [comment]
No plugin installed. I tried firefox and chrome incognito

**Comment by quekky** [comment]
I step through the chrome debugger, it's calling the request function with the correct http url. Must be something else that cause it to call https

In case anyone encounter the same issue, what I did is to open a new tab with https://plex:32400 and accept the cert. After that it seems that the js is able to retrieve the plex api
