### ISSUE TITLE
Some 4k HEVC misdetected as h264 and forcing transcoding

### ISSUE THREAD

**Issue by deanochips** [vexorian/dizquetv#162]
I have a 4k HDR channel 80% of the videos detect and run fine but some miss detect as h264 according to dizquetv logs: 

   videoCodec: 'h264',
  videoWidth: '3840',
  videoHeight: '2160',
  videoFramerate: 60,
  videoDecision: 'transcode',
  audioChannels: '2',
  audioCodec: 'aac',
  audioDecision: 'transcode'

i have attached a video that experiences this problem, you can check for yourself that its HEVC/H265 and hopefully recreate the error

https://drive.google.com/uc?export=download&id=14xZw_n-2GE1-OmsG41gy_KzBn_A9zB9g

**Comment by vexorian** [comment]
Plex is the one that provides this json. Since it also says 'transcode' it means that plex is going to  transcode the hvec as h264. Try adding hevc to the list of allowed codecs in the Plex tab. It could also be because of the bitrate settings

**Comment by deanochips** [comment]
the plex tab already has HEVC, as i said it runs 80% of the 4k stuff fine.

Supported Video Formats : h264,hevc,mpeg2video,av1
Max Playable Resolution: 3840x2160
screenshot: https://i.imgur.com/unpz1Yc.png

and as you can see in plex it is listed as HEVC
screenshot: https://i.imgur.com/XdfGM7B.png

**Comment by deanochips** [comment]
ok i have got it working, but i had to put the max bitrate crazy high "400000", not sure that's intended

but as i have it playing i will close this ticket

thank you for your help and amazing work on this

**Comment by vexorian** [comment]
I just checked your file, the average bitrate is 19000k but as it is a 4k demo, it's very high quality. I suspect there are places where the bitrate is higher than 40k. Or maybe dizquetv's call to plex is bugged. Either way I think this deserves further investigation, so I am reopening it

**Comment by deanochips** [comment]
there was one file that i have that i can't share that even with ridiculous max birtate 8000000 still forces transcode,
 the only way to get it to work was to use -1 which is what i am currently using and is working perfectly for everything i am playing.

that file had a bitrate of 19080 kbps according to plex

**Comment by vexorian** [comment]
After lot's of experimentation, my only conclusion is that this is a Plex quirk. It's counter intuitive that you need 40K bitrate for a 18K bitrate video, but Plex is the one making the decision there.
