### ISSUE TITLE
Filler list items are rendered as a stacked pile instead of a list Mac OS, Safari after 1.1.2 update

### ISSUE THREAD

**Issue by IndecisicveDevice** [vexorian/dizquetv#164]
Using Mac OS 10.16.6 and Safari 14.0

After updating to DisqueTV 1.1.2 the filler lists display not as a list but a stacked pile instead. Since items are stacked in place I cannot see individual items. Previous to the "Filler list" feature, I could see all flex items correctly.

**Comment by vexorian** [comment]
Thankfully, epiphany allows me to test webkit in Linux. Next fix releases will contain the fix.
