### ISSUE TITLE
Create plex playlist from channel

### ISSUE THREAD

**Issue by Frazzer951** [vexorian/dizquetv#165]
It would be great if you could save your channel into a playlist. So I could have my channel setup with my different shows and have them shuffled into a specific order and then save the channel into a playlist, that I can watch too.

**Comment by MoRBiD-MaNGLeR** [comment]
@Frazzer951 You might want to check out the "channel_to_playlist.py" script created by @nwithan8.  After you do your shuffling in dizqueTV, then use his Python script.

Let us know if this fulfills your need or not:
https://github.com/nwithan8/dizqueTV-scripts

**Comment by Frazzer951** [comment]
@MoRBiD-MaNGLeR  It is exactly what I need! Thank You!
