### ISSUE TITLE
No graceful shutdown

### ISSUE THREAD

**Issue by mcbeav** [vexorian/dizquetv#176]
Is there a signal I can send to the docker container running the dizquetv pre-built docker image hosted on docker hub to gracefully shut down the container? When I send the stop signal it seems to forcefully stop the container.

**Comment by vexorian** [comment]
This is a good question and sorry for being neglectful to this project in the last couple of weeks.

I think this is a bug. SIGKILL should always close gracefully and docker sends SIGKILL. The code doesn't have anything regarding graceful shutdown.

That said, this is not usually a problem unless you happen to kill the container just at the same unfortunate time of writing the TV guide.
