### ISSUE TITLE
Please add audio support to channels for content

### ISSUE THREAD

**Issue by serrebi** [vexorian/dizquetv#18]
I am asking for audio support for channels. I want this feature for Audiodrama, and books. Thanks in advanced.

**Comment by psybertech** [comment]
I'd love to see audio settings either per-channel or even at the Plex level.
For me, I would like to see a way to force a particular language if multiple streams are in the video if/when possible.

**Comment by vexorian** [comment]
@serrebi : I am surprised that so many people are asking for this, I think I might upgrade the priority on implementing this. Of course, there's things like auto-tune playlists and supporting sources other than Plex that will come earlier, but I am starting to think there really is a market for audio channels.

@psybertech dizqueTV will play videos with the audio selected for that user for plex. Now the tricky part is having the same show in two different channels but with different languages. What I do to accomplish this is to have two different users , and I added the plex server twice, one for each user. So I use the Spanish user to populate my Spanish channels and the English user for the English channels.

**Comment by MoRBiD-MaNGLeR** [comment]
> @serrebi : I am surprised that so many people are asking for this, I think I might upgrade the priority on implementing this. Of course, there's things like auto-tune playlists and supporting sources other than Plex that will come earlier, but I am starting to think there really is a market for audio channels.

I've been wanting this functionality for a long time, not just for audiobooks, but also to emulate Music Choice channels.  Music Choice channels sometimes have a short playlist or a bad artist.  I realize that a popular workaround is scheduling music videos, but most of us have more music than music videos.  Supporting music playlists would consolidate open apps for me.

Initially, having a channel just play a music playlist would be a good start.  Later on, I'd like to see it configurable to display music trivia related to the artist/track, lyrics (like karaoke does), or even visualizations.

**Comment by MoRBiD-MaNGLeR** [comment]
It would be a niche enhancement, but niche enhancements become feature points to brag and boast about later.

Initially, having a channel just play a music playlist would be a good start. Later on, I'd like to see it configurable to display music trivia related to the artist/track, lyrics (like karaoke does), or even visualizations.

Audiobooks could take advantage of this as well to display trivia related to the author/content, or better yet, a read-along.

**Comment by vexorian** [comment]
I've decided this will be in the next edge release, 1.3.0

Just some gotchas:

* Most likely all that it will do is show the album art, at least in the first edition of this. We would all like to maybe display artist name or artist picture as well as album art, but it's too feature creep for now.
* I am also interested in making an end point that plays a channel (any channel) but just the audio. So you could make "radio stations" this way. So if you only have headphones around you can just listen to the channel's audio, and it wouldn't have to spend system resources transcoding/playing video in that case.

**Comment by palla89** [comment]
I don't know if it's correct to write this here, but would be so cool to have the possibility to specify a video flux and an audio flux, so that for example we can play (muted) videos with chosen audio playlist as soundtrack.
