### ISSUE TITLE
Lower minimum breaks duration?

### ISSUE THREAD

**Issue by scoobshub** [vexorian/dizquetv#183]
We like to use breaks to add little "bumpers" between shows just with our channel logo. It's usually really short videos (like 10-15 seconds); it would be nice -if possibile- to lower the minimum breaks duration option to like 10 sec.

Thanks

**Comment by rebelrickb** [comment]
I think it would be good to be able to run a bumper after the program has finished and before the new program starts with adverts in-between

**Comment by vexorian** [comment]
Is there a reason why it can't be 1 minute? Do you have 1-minute videos that you want to have visible in the guide?

**Comment by scoobshub** [comment]
In my case, we like to have very short breaks just to separate episodes of a tv show. That break is basically a video bumber with just the animation of the channel logo (~10 sec); currently, to avoid problems we loop the same video x3 times to have a clip of 30seconds so we can create the channel Ad Breaks without issues but the result isn't the best :) so just letting the user pick a shorter min duration could really improve this :)

As per your other question (if I got it correctly), I don't think this short break should appear in the guide 🤔

**Comment by vexorian** [comment]
Ah, I misunderstood. I thought you were talking about the channel EPG feature for hiding short clips.

So you are talking about the "Add breaks" button. Ok, I think it's possible to add 10 seconds as an option. Probably will add 15 seconds as well. Though a bit of a problem is that when they are so short, then a delay in playing the previous video will mean that sometimes the break will be skipped.
