### ISSUE TITLE
Option to change server port

### ISSUE THREAD

**Issue by Extarys** [vexorian/dizquetv#186]
Is there an option to change the server port? I can't find the doc for it.

I already have stuff running on 3000, 3300, 8080, 8000, 8888, 8088. :)

Thank you

**Comment by vexorian** [comment]
--port 9999

-p 9999

Arguments work

**Comment by MoRBiD-MaNGLeR** [comment]
@Extarys When you execute dizqueTV from the command-line, you can change the port.  Here's an example using the Windows executable:

dizquetv-win-x64.exe --port 5115 --database D:\dizquetv\.dizquetv

Does this answer your question?  Also, feel free to post support questions in the dizqueTV Discord "general-support" channel or a channel custom to your platform.

**Comment by Extarys** [comment]
:facepalm: Why I didn't think of that.... ARGH

Thank you VERY much! Very excited to try this with Jellyfin! <3
