### ISSUE TITLE
Time Slots: Show's scheduling restarts after 365th episode, raise max to 1000

### ISSUE THREAD

**Issue by MoRBiD-MaNGLeR** [vexorian/dizquetv#188]
On the Time Slots panel, I have a channel set up to run through November 9, 2021 at 02:00 PM.  One of the shows has 891 episodes and is resetting its run after episode S05E41 (the 365th episode) on June 9, 2021 at 01:00 PM.  Why is it restarting?  Is there a hardcoded maximum value of 365 that assumes the user would schedule a maximum of one episode per day for the entire year?  Could we get this maximum removed or at least raised to 1000?

![image](https://user-images.githubusercontent.com/34169521/98603571-202a9600-2297-11eb-898d-a939307f9a77.png)

![image](https://user-images.githubusercontent.com/34169521/98603577-24ef4a00-2297-11eb-9495-68c411039095.png)

![image](https://user-images.githubusercontent.com/34169521/98604160-09d10a00-2298-11eb-9e8c-187339799777.png)

**Comment by vexorian** [comment]
Were more than 365 episodes in the channel before applyting time slots?

**Comment by MoRBiD-MaNGLeR** [comment]
Yes.  The four shows had all of their episodes added to the channel before Time Slots were created.

**Comment by MoRBiD-MaNGLeR** [comment]
The channel's Time Slots didn't save after all of that so I had to recreate them.  While I was at it, I removed all programming from the channel and started over.  This time, the Time Slots allowed the desired setup.  Hopefully, others will be able to avoid a nuclear reset of their channel and have everything work correctly for shows with lots of episodes.  I will close this out.  Thanks.
