### ISSUE TITLE
M3U:  In "group-title" field, allow custom-category suffix

### ISSUE THREAD

**Issue by MoRBiD-MaNGLeR** [vexorian/dizquetv#194]
In the "group-title" field of the M3U, allow a custom-category suffix to be added to allow for dizqueTV channel groups.  Since channels all start with "dizqueTV-", the dizqueTV channels are already grouped together in an IPTV application, but they could be further organized by the second part of the name (e.g., "dizqueTV-KidsMovies", "dizqueTV-KidsTV", "dizqueTV-MoviesHorror", "dizqueTV-MoviesMarvel").  Basically, allow the second part of the name be customizable.  This should be optional of course.

**Comment by vexorian** [comment]
I'll do #106 , which allows customizing the group completely instead of just the suffix.
