### ISSUE TITLE
Jellyfin support?

### ISSUE THREAD

**Issue by Darkwolf1515** [vexorian/dizquetv#2]
Would be fantastic to see it there as well.

Edited: Multiple reports that Jellyfin doesn't work as an IPTV client. Needs some checking.

**Comment by lochstar** [comment]
Agreed. I've tried setting it up in Jellyfin but get an error, "the server isn't sending a compatible media format."

**Comment by vexorian** [comment]
You mean as a player? It's strange it wouldn't like the media format. Most iptv players seem to work fine. And I also tested in emby.

**Comment by Darkwolf1515** [comment]
> 
> 
> You mean as a player? It's strange it wouldn't like the media format. Most iptv players seem to work fine. And I also tested in emby.

Problem is that I cant create the xml file, I can only connect to my plex account to make one, unless there's a way to do so that im not seeing.

**Comment by lochstar** [comment]
@vexorian Yep, Jellyfin as a player. It's set up fine the the XML and M3U files, but when trying to play an error occurs.

**Comment by vexorian** [comment]
We'll have to look further into it for the cause. Maybe it's a codec combination it doesn't like.

**Comment by Darkwolf1515** [comment]
> 
> 
> @vexorian Yep, Jellyfin as a player. It's set up fine the the XML and M3U files, but when trying to play an error occurs.

How were you able to create one using your jellyfin library? I have no idea how.

**Comment by vexorian** [comment]
Ok, one of you folks wants jellyfin support as the media library. This is a feature that's going to be made eventually. We want emby and jellyfin and even youtube  and twitch as sources one day.

The other one wnats jellyfin support as a player , that's something I consider a bug, it should already be working on any IPTV client.

**Comment by Darkwolf1515** [comment]
> 
> 
> Ok, one of you folks wants jellyfin support as the media library. This is a feature that's going to be made eventually. We want emby and jellyfin and even youtube and twitch as sources one day.
> 
> The other one wnats jellyfin support as a player , that's something I consider a bug, it should already be working on any IPTV client.

Oh, so they made their series in plex, streamed from plex, but jellyfin just plays it. That makes more sense.

Can't wait to see the full support, thanks for keeping this alive!

**Comment by vexorian** [comment]
I just tested to setup dizquetv in jellyfin. It works all right. No surprise because I've been using it in emby and these two services seem to be mostly the same.

The recommended way to setup dizquetv in jellyfin is as a m3u tuner. If it has trouble playing the content that's an issue specific to your configuration and you should try creating another issue or going to ask in the discord about it.

**Comment by Darkwolf1515** [comment]
So since this was closed, does that mean Jellyfin as a media source is on hold/abandoned?

**Comment by vexorian** [comment]
It has to be created as a different issue or it gets confusing.

**Comment by Darkwolf1515** [comment]
Strange how I have to make a second issue for the same thing considering I made this one and it was taken over, but oh well.

**Comment by technificentConsulting** [comment]
I'm too would like the ability to use Jellyfin and would like to know what I need to do to help out the development efforts?   If this is not the right place to discuss please advise.

**Comment by vexorian** [comment]
Closed. Issue for jellyfin source is at #98
