### ISSUE TITLE
Crashes on launch [1.2.2]

### ISSUE THREAD

**Issue by notanewbie** [vexorian/dizquetv#208]
I'm trying to get a DizqueTV server up and running at home, but for whatever reason it crashes whenever I try and run it. What might cause this?

**Comment by vexorian** [comment]
try to catch the logs.

**Comment by vexorian** [comment]
Hey ... by any chance are you trying to double click on the exe?

**Comment by MoRBiD-MaNGLeR** [comment]
@notanewbie Are you Sleepykid, and did we already address this in the Windows text channel of the Discord?

You should be providing it with parameters.  Example:
dizquetv-win-x64.exe --port 8000 --database .dizquetv

If using CMD/PowerShell, it's best to create a BAT/CMD/PS1 with everything self-contained.

Let us know if this is still an issue or not.

**Comment by notanewbie** [comment]
No I'm not sleepykidd, but yeah I figured it out, the issue was I was just trying to open the exe file instead of running a bat file

**Comment by notanewbie** [comment]
My code is actually different than that, I'm using the code I'd previously been using for PseudoTV:

cd [location]
start /min dizquetv-win-x64.exe -h [IP address] -p 8000
