### ISSUE TITLE
Radio channels

### ISSUE THREAD

**Issue by spicerackk** [vexorian/dizquetv#21]
Is it at all possible to add the ability to have music only channels? 

Until I am able to incorporate Spotify into Plex (if at all), having a way to simply chuck on a music only channel from the Live TV/DVR could be a useful way to circumvent that. 

Could even have an option to include radio streams using a link?

**Comment by vexorian** [comment]
I think Plexamp is pretty okay at that. Radio channels are a thing that gets requested often. I am not sure if it will happen as being able to create TV programs that just play music or if maybe we'll be able to create our radio stations, because just like IPTV there's something similar for radio stations.

**Comment by MoRBiD-MaNGLeR** [comment]
It would be a niche enhancement, but niche enhancements become feature points to brag and boast about later.

I've been wanting this functionality for a long time to emulate Music Choice channels. Music Choice channels sometimes have a short playlist or a bad artist. I realize that a popular workaround is scheduling music videos, but most of us have more music than music videos.

Initially, having a channel just play a music playlist would be a good start. Later on, I'd like to see it configurable to display music trivia related to the artist/track, lyrics (like karaoke does), or even visualizations.  Audiobooks could take advantage of this as well to display trivia related to the author/content, or better yet, a read-along.

**Comment by vexorian** [comment]
Let's have all the discussion about this kind of thing in #18
