### ISSUE TITLE
Feature request: Add CUID tag to m3u

### ISSUE THREAD

**Issue by ReenigneArcher** [vexorian/dizquetv#212]
Please add the CUID="" tag to the m3u list.

This is channel unique id. This helps iptv clients keep the channel mapping even if the channel name changes.

https://forums.plex.tv/t/xteve-iptv-for-plex-dvr/278500/826

**Comment by vexorian** [comment]
I wish there was like a good documentation for all the stuff that can be done with the m3u format. This sounds like a must have .

**Comment by ReenigneArcher** [comment]
@vexorian This is definitely not complete, but many channel attributes are listed here. https://en.f-player.ru/extm3u-iptv-format

And an example channel built by xteve is listed like so. I think CUID and channelID may be equivalent, but I am not positive. I know CUID works as channel unique ID when importing into xteve (screenshot below).
`#EXTINF:0 channelID="x-ID.69" tvg-chno="3085" tvg-name="fubo Sports Network" tvg-id="3085" tvg-logo="http://localhost:34400/images/4417749f7e8f029bc8a6f6d7717cf3ed.png" group-title="Sports",fubo Sports Network`

I have 1 playlist that contains CUID for each channel.
![image](https://user-images.githubusercontent.com/42013603/102703742-c7103380-4240-11eb-9ac3-912eba03deb9.png)

I'm not sure why they use #EXTINF:0 and not #EXTINF:-1... I thought -1 was for unknown stream lengths. Definitely difficult to find all the attributes that can be used.

**Comment by ReenigneArcher** [comment]
I just modified my m3u to test.

The following attributes all work as unique ID:

- CUID
- channelID
- id

**Comment by nwithan8** [comment]
> I wish there was like a good documentation for all the stuff that can be done with the m3u format. This sounds like a must have .

https://tools.ietf.org/html/draft-pantos-http-live-streaming-08#section-3.3
https://github.com/globocom/m3u8/blob/master/m3u8/model.py

**Comment by vexorian** [comment]
I have tried adding CUID , channelID and id and the results are honestly pretty bad. Unsure if I am doing something wrong (I am using the channel number as id) but in xteve at least it seems to be doing the opposite of what was intended. Every time I edit a channel now it creates duplicate entries in the xteve list.

**Comment by ReenigneArcher** [comment]
> 
> 
> I have tried adding CUID , channelID and id and the results are honestly pretty bad. Unsure if I am doing something wrong (I am using the channel number as id) but in xteve at least it seems to be doing the opposite of what was intended. Every time I edit a channel now it creates duplicate entries in the xteve list.

Could you share the m3u?

Are you adding all 3? It should be just one of those 3 tags (they're equivalent).

**Comment by vexorian** [comment]
I'll try with just one

**Comment by vexorian** [comment]
Looks like only CUID does help, at least with xteve channels keep their settings even after a name change

**Comment by ReenigneArcher** [comment]
Nice! Looking forward to the new version

**Comment by ReenigneArcher** [comment]
Thanks for adding this feature!
