### ISSUE TITLE
Unable to play channel

### ISSUE THREAD

**Issue by wilsonrx** [vexorian/dizquetv#22]
Using MacOS installer and 0.0.60.  Created a couple of channels.  Upon playing content, Plex gives a generic error.  In the Plex logs it says:

Aug 14, 2020 14:25:56.533 [0x70000ea22000] ERROR - Unable to find title for item of type 5
Aug 14, 2020 14:25:56.533 [0x70000ea22000] ERROR - Unable to find title for item of type 5
Aug 14, 2020 14:25:56.554 [0x70000d839000] ERROR - [Transcoder] http://127.0.0.1:8000/video?channel=2?transcode=heavy: Server returned 5XX Server Error reply
Aug 14, 2020 14:25:56.555 [0x70000ea22000] ERROR - Failed to start session.
Aug 14, 2020 14:25:56.555 [0x70000ea22000] ERROR - Recorder: Unable to create transcode session or session failed to start.
Aug 14, 2020 14:25:56.555 [0x70000ea22000] ERROR - Recorder: Error 16 (Recording failed. Please check your tuner or antenna.) starting the record, shutting things down.
Aug 14, 2020 14:25:56.555 [0x70000dd57000] ERROR - Subscription: Rolling media grab failed to start.
Aug 14, 2020 14:25:56.556 [0x70000ea22000] ERROR - Grabber: Starting media grab failed.
Aug 14, 2020 14:25:56.556 [0x70000ea22000] ERROR - Unknown metadata type:

**Comment by vexorian** [comment]
Try getting dizquetv's logs. Most likely your ffmpeg is not setup correctly.

**Comment by MoRBiD-MaNGLeR** [comment]
@wilsonrx Please provide your dizqueTV logs so your ffmpeg setup can be reviewed.

**Comment by wilsonrx** [comment]
Where can I find the logs?

**Comment by MoRBiD-MaNGLeR** [comment]
@wilsonrx Regarding the logs --

Log data writes to the console so you'd need to copy the console output and provide that.  @vexorian might have a better way for you to capture log data.  If you're in Linux, you can modify your execution script to use the Tee command to output to both console and a file.

Here's how I instead write the console output to a log file in Windows.
C:\dizqueTV\dizquetv-win-x64.exe --port 8000 --database C:\dizqueTV\.dizquetv >> C:\dizqueTV\dizqueTV.log 2>&1

This appends both the regular output and the error output to a log file.  Replace the paths with your own values.  After you capture data to the log, provide that to @vexorian for review.

**Comment by wilsonrx** [comment]
Correct, the ffmpeg path was wrong.  I had tried two different ways to install ffmpeg and had the wrong path in dizquetv settings.  It seems to be working now!
