### ISSUE TITLE
1.2.3 Log:  "Couldn't get DVRS list from PLEXSERVER" should be logging as informational/warning, not error

### ISSUE THREAD

**Issue by MoRBiD-MaNGLeR** [vexorian/dizquetv#228]
Version 1.2.3 Log Error:

`Couldn't get DVRS list from PLEXSERVER. This error will prevent 'refresh guide' or 'refresh channels' from working for this Plex server. But it is NOT related to playback issues. Error: GET /livetv/drs failed: Hostname/IP does not match certificate's altnames:`...

I understand why I got this -- I don't have dizqueTV channels set up in Plex.  A few versions ago, I migrated the dizqueTV channels over to Jellyfin and removed them from Plex.

Since having dizqueTV channels in Plex is not a requirement, rather than logging as an error (RED) in the log, this should be logging as informational/warning (YELLOW) in the log.

**Comment by vexorian** [comment]
it logs as red!?

**Comment by vexorian** [comment]
With #304 this can actually be controlled. If user doesn't care about the update, they should disable the send channel updates. So I think it can stay as error now that the behavior can be disabled.
