### ISSUE TITLE
Can you build a channel from a plex collection?

### ISSUE THREAD

**Issue by cbarbara** [vexorian/dizquetv#23]
When building a station I see my libraries show up and my playlists. But it would be helpful if I can make a station out of a plex collection I already have built.

**Comment by vexorian** [comment]
This is something I actually need for my own use. The only thing stopping me is I don't know how to access collections in the plex api. But it will happen eventually.

**Comment by cbarbara** [comment]
thanks!
For another similar thought, if there is a way to go any additional filtering on the libraries (ex: by genre) that would also be really helpful.

**Comment by vexorian** [comment]
0.0.61 supports collections. I am closing it. Please make another issue for the genre filtering. It's not possible at  t he moment, but could be a feature request.
