### ISSUE TITLE
Tweak Weights: Split "by Time" (like now) and "by Quantity"

### ISSUE THREAD

**Issue by psybertech** [vexorian/dizquetv#26]
Hi there, love this so far!!!

Question, or am I not seeing it...
the weighting option doesn't seem to impact the shuffle options.
Am I just not seeing it and my random shuffles are just hitting odd rands or is this weighting only applied at the time it is changed ignoring the shuffle types afterwards?

I read the help on weighting and balancing, but I am not sure if weighting affects the shuffle options.

My use example:

5  shows, I weight them as 20, 40, 60, 80 & 100.
I set the number before randomize to '2' and try the shuffle options ( block, random,cyclic), the number '2' doesn't get  honored except for block (probably by design there and thats OK but would be great if it was 'global' for the shuffles), but the weighting doesn't really seem to be honored in my _limited_ tests. I only have 10 channels so far.....

Am I just not seeing it in the long view of the shuffle? I tend to only look at the top 20-40 or so... not too much.

Anyway...... 
_Sorry for posting a question in the issues, but I can't find an official 'forum' for dizquetv to ask user questions yet._

Thanks!!!
j

**Comment by vexorian** [comment]
@psybertech : Yes, the number is only used by block shuffle. 

Weight is time-based, not quantity based. What it means is that if for example, there are two TV shows. One TV has 12 one hour-long episodes and the other show has 24 half hour episodes. These shows are actually already "balanced" , because the total show length for both shows is 12 hours.

Now if I wanted the second show to be twice as frequent as the first show. We would need 12 episodes of the first show and 48 episodes of the second show. So my tip is: When trying to see if weights are working, don't focus on which show appears more times in the list, but which show's total duration is longer.

**Comment by psybertech** [comment]
Thanks, @vexorian 

Understood!

I was just hoping for a 'only show each show twice' thing, so you could see a back to back airing and then move on. If you tune in part way thru the first, then at least the next would be the same show... or a new one, and so on.

Got it.

I have another question I will post soon... sorry again for posting questions in the 'issues' section.

cheers!
j

**Comment by vexorian** [comment]
Does it sound like what you want is something like Block Shuffle, but where you can select the number of times each show appears in a block, instead of making it count for all shows? I think it can be done.

**Comment by psybertech** [comment]
To be honest, I just started playing with this yesterday, so I don't have any real experience on what I really want to see.
In my head, I just want to see no more than X episodes of a single show in a row, but have the ability for some shows to come back more often... kinda like they are more popular and, but yet I can still squeek in some shows that are under-appreciated, all while having the same basic guide of 'no more than X in a row', but it would be ok to have a show rotate out, play another show for X and if the random gods deem it so, then the heavily weighted show comes back right after.

In my head I get it. haha

But I am all for more options.
Since I have just started to scratch the surface, I am not sure what I really want to do yet and each channel has the potential for different things.

And to be honest... this is something I have wanted for OVER A DECADE!!!
I've been using HTPC/media servers/etc, since the original Xbox via the first XMBC and always wanted my own channels.
My only method of doing so was straight up shuffled playlists, and well, that just sucked.
So this is the first EXCITING thing I have seen in a loooong time.
I don't even use plex other than a backup server for EMBY, but I am glad I do! =D

Thanks again!!!!

cheers
j

**Comment by MoRBiD-MaNGLeR** [comment]
@psybertech At this point, what would you like to do with this issue/question?  Are you wanting an enhancement request to limit quantity per show for the Block Shuffle tool, or are you good with closing this out?

**Comment by psybertech** [comment]
I guess I would like and enhancement.
To be able to use the weight and have it applied to whatever shuffle option is used if possible.

So, for random shuffle, an example:
5 shows all with 5 or more seasons each
1 show with 10+ seasons
1 show with just one...
I want to weight the 1 show with one season very high, giving it a better chance on popping up, weight the one show with 10+ seasons pretty low and then weighting the others somewhere else in the middle... not sure where until I can see it sort of working. But in my head this makes sense and its just a basic example really.

Thanks

J

**Comment by MoRBiD-MaNGLeR** [comment]
@psybertech Does this Description capture your Enhancement Request?:
**Tweak Weights: Split "by Time" (like now) and "by Quantity"**

**Comment by psybertech** [comment]
If QTY = amount of episodes, then yes.
Thanks!

**Comment by MoRBiD-MaNGLeR** [comment]
Yes, QTY = amount of episodes.  Thank you for confirming.

**Comment by vexorian** [comment]
Random slots in 1.3.0  are a good replacement for this. By playing with time, duration and weight you can control both the frequency and the time weight with more granularity. So I am closing this
