### ISSUE TITLE
Run as a service

### ISSUE THREAD

**Issue by mbrickett** [vexorian/dizquetv#261]
I use NSSM to install as a service. This way it will start automatically on boot and restart if it shuts down unexpectedly.

http://nssm.cc/usage

**Comment by MoRBiD-MaNGLeR** [comment]
It is not on the product roadmap to install the Windows executable as a service.  Development time and effort is being placed on platform-agnostic changes.  Using NSSM as you've done is the recommended process to install the Windows executable as a service.  Closing.
