### ISSUE TITLE
Can't Run DizqueTV Today (version 1.30)

### ISSUE THREAD

**Issue by GlobalServer500** [vexorian/dizquetv#279]
I noticed today that I can't seem to load the dizquetv. I get this error message now.

"Couldn't get DVRS list from Global Entertainment Network. This error will prevent 'refresh guide' or 'refresh channels' from working for this Plex server. But it is NOT related to playback issues. Error: GET /livetv/drs failed: connect ETIMEDOUT 192.XXX.X.XX:32400
    at Plex.GetDVRS (C:\Users\xlogo\Downloads\src\plex.js:147:13)"

not sure what happened, all I remember is deleting and renumbering some channels, then restarting my computer and now the channels directory for .dizqueTV is empty and I get that error message and it does not connect to the dizqueTV website. I have used DizqueTV about 4 months now, but this is the first time this happened. Can someone explain this? I am using version 1.30. Thanks.

**Comment by vexorian** [comment]
It's timing out when contacting plex. Also that error does not stop dizquetv from starting, the real issue is likely something else in another log

**Comment by GlobalServer500** [comment]
Thanks, is there a way to fix this? I deleted and re-downloaded dizquetv 1.30, still getting same error. I tried loading the m3u file to run on vlc, but its still not doing anything.

Your input can't be opened:
VLC is unable to open the MRL 'http://192.XXX.X.XX:8000/video?channel=500'. Check the log for details.

i'm not tech savvy, how do I check logs?

**Comment by vexorian** [comment]
The thing is that if it is the connection with plex that's timing out, then it is a plex connectivity issue. Reinstalling dizquetv won't fix it. You need to research into why the plex address isn't working.

If you go to dizquetv settings, do the plex ui and backend routes show up as working?

**Comment by GlobalServer500** [comment]
plex works for streaming my files, and I just downloaded the log files (I can add them or send them if you want)?

I can't load dizquetv anymore to check the settings. http://192.XXX.X.XX:8000/

I get this error message "This site can’t be reached192.XXX.X.XX took too long to respond.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_TIMED_OUT"

the dizquetv .exe loads up but it gives the error I posted originally on this thread.

**Comment by vexorian** [comment]
It's the connection from dizquetv to plex.

Sure if you go to plex on your own it will work. But for some reason it isn't working from dizquetv

> If you go to dizquetv settings, do the plex ui and backend routes show up as working?


Try the discord as real time might be better way to help

**Comment by GlobalServer500** [comment]
Okay, I will try the discord later. I'm out right now, but will ask on discord later on.

**Comment by GlobalServer500** [comment]
I fixed the issue, so I guess there is no need to go on discord now. Had nothing to do with Dizquetv or Plex. Everything runs fine now. It was my firewall settings that were causing the issue, but now it is resolved.  Thanks for the assistance.
