### ISSUE TITLE
Custom Port Configuration - Empty Response

### ISSUE THREAD

**Issue by phillipsmn** [vexorian/dizquetv#281]
I'm trying to run dizquetv on Synology via Docker and I have set the port to run at 8008 (portainer is at 8000). When I start the container, portainer recognizes it as publishing at 8008, but nothing renders when I open the page. I get an `ERR_EMPTY_RESPONSE` code when trying to access the page in the browser.

Below are the final lines of the log file. It doesn't appear to be odd to me, other than the custom port assignment seems to be happening after the server is started at the default port.

````
dizqueTV 1.2.4
|:::///### o |
|:::///###   |
':::///### o |
'------------'
.------------.

Successfully connected to : ./.dizquetv
DB Version correct: 703
HTTP server running on port: http://*:8000
Internal TV Guide data refreshed at 3/11/2021, 7:37:51 PM
XMLTV Updated at  3/11/2021, 7:37:51 PM
-p 8008
````

**Comment by vexorian** [comment]
For docker it's not necessary to configure dizquetv's port. Instead configure docker's port redirection. Host should have the port you want (8008) and container should stay at 8000. Then you can redirect host port 8008 to container 8000.

**Comment by phillipsmn** [comment]
That sorted it. Thanks!
