### ISSUE TITLE
(FEATURE REQUEST) Opacity in Logo

### ISSUE THREAD

**Issue by jello042** [vexorian/dizquetv#303]
I was wondering if there is a way to adjust the opacity? I tried making an opacity logo but it displays in full opacity with a drowned out color. Is there a way to make it transparent????

Also, was wondering if there is any plans or way to have a timed logo? (something that can display once every 10 minutes for 10 seconds,etc...) or ability plans to have the ability to use more than one logo? If not, that is fine....but the transparent logo is my top priority question. Thanks!

**Comment by rebelrickb** [comment]
Would also like a logo that is timed. For example comes on 1 minute after program started and goes off 2 mins before end off the program

**Comment by vexorian** [comment]
It's now possible to use a different image file for the channel logo and the watermark. So you can have the watermark be a 50% opacity version of the channel logo.
