### ISSUE TITLE
A tv show that is added to more than 2 collections, appears only in two of the collections in the library browser

### ISSUE THREAD

**Issue by nacho1191** [vexorian/dizquetv#308]
Hello, I detected that dizquetv only pick the first collection associated to the media, hope can be fix it.

**Comment by vexorian** [comment]
I tested this. And actually the two collections appear.

There is a check that prevent collections  from appearing if they only have one movie. I think this may have caused your confusion here.

I will remove this check in 1.4.2. I am guessing that even though the collection has only 1 element, there's a reason why the user wanted it to be a collection.

**Comment by vexorian** [comment]
Closing it, but if you notice the problem with collections with more than 1 item, then that's indeed a bug and feel free to reopen the issue in that case.

**Comment by nacho1191** [comment]
hello, to me doesn't appear. maybe it's because i have more than 2 collections for the same tv show.
http://prntscr.com/12zy98z

http://prntscr.com/12zydvr

**Comment by vexorian** [comment]
I just tried with TV shows and they both show up. Something else must be going on here. 

* Does the show appear outside the collection?
* Are all shows in the same library?

**Comment by nacho1191** [comment]
Does the show appear outside the collection?
A: yes outside, and appear into the first two collections too.

Are all shows in the same library?
A: what do you mean? the collections are into the same section where are the tv shows too.

**Comment by nacho1191** [comment]
I checked now with a movie, and I can say dizquetv only detect the first two collections for one item, if you have more than two, doesn't show up into the others collections.
