### ISSUE TITLE
Break Fork Relationship

### ISSUE THREAD

**Issue by anthonylavado** [vexorian/dizquetv#315]
Hey there!
Would you consider breaking the fork relationship?

Since this repository is a fork of another one, a lot of GitHub features get disabled, and it's harder to discover. For example, it doesn't show up in search (see [here](https://github.com/search?q=dizquetv)), and code search is disabled.

If you contact GitHub Support, they'll be able to "break" the fork relationship, so that this repo can stand on its own. We had to do this for a few things over at Jellyfin.

Thanks!

**Comment by vexorian** [comment]
Yeah I constantly have to deal with issues like this. And submitting PRs defaults to pseudo tv.

I didn't know you can do it contacting github support. Will try.

**Comment by anthonylavado** [comment]
I see this is complete now. Thanks for following up on it!
