### ISSUE TITLE
Default “Send Channel Updates” to False

### ISSUE THREAD

**Issue by curiousblueprints** [vexorian/dizquetv#336]
I’d like to consider defaulting the “Send Channel Updates” option in Plex server settings to false on new installs. Here is why:

If it is off, and you only use DizqueTV channels, you have to go manually scan/update channels in Plex, a minor inconvenience.

If it is off, and you use Xteve/other non-DizqueTV channels, you still have the manual update.

If it is on, and you use DizqueTV only, it automatically updates your channels, which is a minor convenience.

If it is on, and you use Xteve/HDHomeRun, it’s a live-TV breaking show stopper.

Defaulting to on defaults to a minor quality of life feature for exclusive DizqueTV users, but breaks all other live TV for those using multiple sources.

Case in point: https://www.reddit.com/r/dizqueTV/comments/o7w35x/hdhomeruns_and_dizquetv_together/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

I understand that there is the wiki entry, but for some reason it is difficult to find.

**Comment by cchiapusio** [comment]
Agreed, this was a difficult to find solution and would benefit from being exposed in the UI regardless of default settings.

**Comment by vexorian** [comment]
I am not sure I agree with the "minor inconvenience" / "minor convenience" assessment.  It really depends on how many people use dizquetv alone versus how many people use it with hd homerun. What seems like a good idea is to add a warning or something that explained that this would break xteve.

**Comment by vexorian** [comment]
Ok I actually read the reddit thread. If Plex deletes all channels, that's pretty dumb. I will disable it by default.

**Comment by vexorian** [comment]
Unsure why I hit close with comment. It's actually in development
