### ISSUE TITLE
Audio Volume Changes On Different Files/Clips

### ISSUE THREAD

**Issue by GlobalServer500** [vexorian/dizquetv#353]
I have enabled "Audio Normalization" but when my dizqueTV channel is played on other peoples tv sets the audio volume changes on each clip. Is there a way to fix this?

**Comment by vexorian** [comment]
Audio normalization doesn't normalize volume. It normalizes audio lengths. Some files have audio streams that are shorter than their video streams, which makes the concatenation fai.

I would love to have volume normalization, unfortunately, it is not possible to normalize volume on the fly, and Plex doesn't expose volume normalization data for video files. If they did, implementing volume normalization would be easy

**Comment by vexorian** [comment]
Added wontfix tag because I can't implement volume normalization until Plex adds the metadata.

If plex ever add it, I will most likely implement it on that same day because it is something I really want to have.
