### ISSUE TITLE
Music videos seems to have 2 guide issues.

### ISSUE THREAD

**Issue by DevXen** [vexorian/dizquetv#361]
I added a library for all my music videos. 

Sometimes they show in the guide right. but mostly it'll extend the single music video to be around 20mins to a couple hours. (plays different videos in that time)

[https://i.imgur.com/t9uIZ31.jpg](url)

and many times it'll just show the channel name for blocks.
[https://i.imgur.com/OyuJJgj.jpg](url)

I don't have allowed start times set at all. no padding. and no flex. though i have tried those and haven't been able to fix these issues. - it's weird cause my red vs blue episodes are only a few minutes long and it doesn't do this.  though this might be due to my having to do an 'other' library for the music videos. i'm not sure. 

I have also tried the flex recipe for music videos which is great as far as random goes but it bothers me not being able to see what is playing. 

-Dev

**Comment by vexorian** [comment]
This is controlled by "Minimum program duration to appear in the TV guide (seconds-)" option in the EPG tab in the channel configuration.
