### ISSUE TITLE
Improve xml epg data

### ISSUE THREAD

**Issue by ReenigneArcher** [vexorian/dizquetv#362]
Some suggestions for improving the epg data. (I believe this is related to https://github.com/vexorian/dizquetv/issues/297)

Ideally all the metadata that is available should be added according to the xmltv standard available [here](https://github.com/XMLTV/xmltv/blob/master/xmltv.dtd) or [future version](https://github.com/XMLTV/xmltv/blob/master/todo/xmltv-0.6.dtd)

Date should be added in this form; however Plex does not recognize the standard method. They do recognize the others below.
```xml
<date>20110101080000 +0000</date>
```

If the full date is not known then you use as much information as possible.
Year, Month, and Day
```xml
<date>20110101</date>
```
Year only
```xml
<date>2011</date>
```

A more full example
```xml
	<programme start="20210825094900 +0000" stop="20210825105200 +0000" channel="3000">
		<title lang="en">The Walking Dead</title>
		<desc lang="en">Rick and Carl look for shelter while Rick deals with old wounds; those left at the prison consider whether survival alone will be enough.</desc>
		<length units="seconds">3780</length>
		<date>20140209</date>
		<sub-title lang="en">After</sub-title>
		<icon src="https://metadata-static.plex.tv/1/gracenote/1a048479bd4c4c54324997e1178e0c92.jpg" />
		<episode-num system="onscreen">S04E09</episode-num>
		<episode-num system="common">S04E09</episode-num>
		<episode-num system="xmltv_ns">3.8.</episode-num>
		<episode-num system="plex">5fc6f50ca05ef8002e5fe380</episode-num>
		<rating system="TV Parental Guidelines">
			<value>TV-MA</value>
			<icon src="https://loyoladigitaladvertising.files.wordpress.com/2014/02/nr-logo.png" />
		</rating>
		<category lang="en">Drama</category>
		<category lang="en">Horror</category>
		<category lang="en">Science fiction</category>
		<previously-shown start="20140209 +0000" />
		<video>
			<present>yes</present>
			<aspect>16:9</aspect>
			<quality>HDTV</quality>
		</video>
	</programme>
```
I think these are not included or should be improved in current epg from dizquetv

video/quality = HDTV, 1920x1080... IF set to "HDTV" plex will show this as an HD video (web UI only, not on Shield ???)
rating/system = MPAA (motion picture association of america), TV Parental Guidelines (US tv ratings), etc., etc. (don't know if you can actually get this from Plex metadata, might need to have a rating lookup dictionary)

I believe you can also load in roles/actors. Not sure how to load a background/fanart image but I believe that is also possible. If you figure this out please let me know as I'm working on a related project that would benefit from it.

**Comment by ReenigneArcher** [comment]
If you add the HDTV quality tag Plex will know the channel/program is HD.

![image](https://user-images.githubusercontent.com/42013603/131270705-2bb4428a-c528-42d2-b2f4-2b484c04431d.png)

Probably doesn't matter much for dizquetv, but this is how Plex uses the "Prefer HD" option in the DVR.

**Comment by vexorian** [comment]
It's actually really convenient that Plex thinks the stream isn't HD. Because then you can enable "Prefer HD" to stop it from recording the "DVR" to the hard drive.

**Comment by ReenigneArcher** [comment]
That won't prevent it from recording, it will just try to find the show/movie on another HD channel before falling back to the non HD channel.
