### ISSUE TITLE
Repeating Block Schedules

### ISSUE THREAD

**Issue by Sperryfreak01** [vexorian/dizquetv#37]
I tried to write this out like I think it would work, feel free to adapt as needed. 

## Request:
Add a new schedule format, that allows for repeating a block of shows

## Goal
Allow users to schedule blocks of content that have a higher chance of being seen throughout the day.

## How it works:
Build a block of shows of a fixed but selectable length and then have those blocks replay a fixed but selectable number of times.
After the rerun count expires a new block of content it created. 
The rerun block would support block shuffle
- If all shows can not be fit into the block due to time constraints then the show index spills over into the next rerun block.
  or
- If all shows can not be fit into the block shuffle  due to time constraints then the rerun block is expanded to contain all  
   episodes and the rerun block is modified to maintain the 24 hour time.  Flex time can be used to expand the rerun block to 
   something that can divide 24 evenly.
- If all shows can not be fit into the block shuffle  due to time constraints then the rerun block is expanded to contain all  
   episodes and it will spill over the 24 hour window depending on the rerun counter.

**Comment by vexorian** [comment]
I think Random Slots in 1.3.0 or Time Slots in 1.2.0  kind of allow this. Closing it but make sure to open a new issue if they are not enough for you
