### ISSUE TITLE
Programming Start Reset

### ISSUE THREAD

**Issue by ados8** [vexorian/dizquetv#371]
First, thank you for the development time into bringing this service back.
I started to look into pseudotv and after hours found even the Plex version just wouldn't work.

I'm not sure if this is a feature or bug but whenever you open a channel for edit the "Programming Start" resets to the nearest 30 minute time. This is incredibly annoying when you want to update a flex or just randomise the channel and now its got a new start time. 

Can we have either a setting to toggle off or just have it auto set time when the channel is being configured but thereafter its fixed unless the user changes it.

Thanks 😊

**Comment by vexorian** [comment]
It's a feature. It doesn't change the schedule or is supposed to change at all, it just displays the  currently-playing item at the top. I guess I need details as to what detriment this is causing.

**Comment by vexorian** [comment]
Forgot to say, you can use the Fast Forward / rewind tools to fix work around it
