### ISSUE TITLE
Add tvg-chno tag to m3u file

### ISSUE THREAD

**Issue by Browneye3001** [vexorian/dizquetv#38]
In the m3u file some IPTV players require the tvg-chno field to set channel numbers in a channel list.

Example:

`EXTINF:0 tvg-id="122" tvg-chno="122" tvg-name="Cartoon Network" tvg-logo="http://192.168.xx.xx:8000/images/Cartoon.png" group-title="dizqueTV",Cartoon Network
http://192.168.xx.xx:8000/video?channel=122`

The tvg-chno='xxxx' is inserted after the tvg-id variable. The tvg-id is used for linking to the epg xml, the tvg-chno is for defining the channel number in a player.

**Comment by MoRBiD-MaNGLeR** [comment]
Reviewing other apps/dev online, I've noticed that 'tvg-chno' is implemented, roadmapped or being discussed for Jellyfin, Emby, Tvheadend, TiviMate and IPTV Simple Client.

'tvg-chno' corresponds to the channel number and displays next to the channel name.

'tvg-id' (which we use now) corresponds to the 'channel-id' field in the EPG xml file.
If missing from the M3U file, sometimes the 'tvg-name' tag is used to map the channel to the EPG.  [I'm wondering if 'tvg-id' missing is what caused 'tvg-name' to be '007' and '1979'.]

There's nothing to say that we can't populate 'tvg-id' and 'tvg-chno' with the same value.

**Comment by vexorian** [comment]
I have this added in the dev branch. Can you name a player that needs this so that I can test it?

**Comment by roormonger** [comment]
Emby uses it.

**Comment by vexorian** [comment]
Hmnn I've been using emby's live tv thing for ages and never noticed any issues. @Browneye3001  Can you elaborate what problems you've experienced?

**Comment by Browneye3001** [comment]
Hey @vexorian I use dizquetv on the NVidia Shield 'Channels App' The channels app is an agregator for other devices/sources under the one app. To enable IPTV sources in 'Channels' there is another app called 'TVirl'. This then feeds into the channels app to allow HDHomerun tuner channels as well as dizquetv channels all in the one app. I haven't set dizquetv up in Plex as my current HDhomerun tuners use an external XML file as a guide and as you kowo Plex can't handle more than one external XML file.

TVirl reads the m3u from dizquetv, however when it found no tvg-chno tag in the m3u it then tries to assign arbritary numbering to the channels (e.g. 001, 002,.....it doesn't use the tvg-id tag). I manually added the tvg-chno tag in the m3u file and TVirl recognised all of the channel numbers and used them.

I did do a test where I installed dizquetv on Plex. Plex seemed more interested in service names rather than channel numbers, the only real time it is needed is when you link the tuner channel line up with the services found in the EPG xml. After that I don't think Plex needs to know about channel numbers.

In 'Channels' on the Shield though it is more like a normal channel switching app whereby you can use a channel up/down button on a remote to change what you are watching. Defining the channels in the m3u allows you to specify the numbers so that there is no clash with other channel sources. 

Maybe when you define the channel in dizquetv there should be two numbers. a service ID (tvg-ID) and the channel number (tvg-chno). I've worked a bit with EPG xml's for Broadcasters (Cable and Terrestrial) and there is usually two different defintions of a service as previously outlined.

**Comment by MoRBiD-MaNGLeR** [comment]
I recommend that we populate 'tvg-id' and 'tvg-chno' with the same value.

**Comment by Browneye3001** [comment]
> I recommend that we populate 'tvg-id' and 'tvg-chno' with the same value.

That would work for me. Having seperate id and chno is really more for advanced rebroadcast systems.

**Comment by Browneye3001** [comment]
Implmented. Thanks to all.
