### ISSUE TITLE
How do I add a Plex server?

### ISSUE THREAD

**Issue by CHJ85** [vexorian/dizquetv#383]
Hi there. I'm trying to add a Plex server. When I click the "Sign in / add servers" button, it says I have 2 minutes to do so.
No login screen or anything pops up.
So I open up a different tab and login to my Plex server, but it still doesn't let me add it.
This is confusing. What am I supposed to do here?
And also, what's with the 2 minute window? Kinda stressful if you use two-step authentication.

**Comment by vexorian** [comment]
Your browser is probably blocking the popup window. And as long as you are already logged into plex, you won't need to setup your credentials or input two factor, just click an accept button.

**Comment by CHJ85** [comment]
Oh thanks @vexorian  . That was easy. Now I feel silly. 😀
