### ISSUE TITLE
If I change my Plex password, would I need to login again?

### ISSUE THREAD

**Issue by CHJ85** [vexorian/dizquetv#385]
Hi there. If I change my Plex password, will dizque still remember my server?
Reason I ask is because dizque saves the user access token.

**Comment by vexorian** [comment]
It saves the token. I am not sure if changing the plex password changes the token. But there have been cases of the token stopping working in the past when Plex is restarted or something like that.

In case the token no longer works, you can replace it in dizqueTV's plex server config and it should work just fine from then on.

**Comment by CHJ85** [comment]
Thank you!
