### ISSUE TITLE
Channel Watermark - Transparency

### ISSUE THREAD

**Issue by fkick** [vexorian/dizquetv#387]
Hello, 

Just started dipping my feet in with dizquetv and loving it so far.

Is there support transparency in png files when using them for Channel Watermarks? In my tests I've been unable to get any transparency or opacity settings to work, and all the watermarks are ending up with solid white backgrounds.

Thanks!

**Comment by vexorian** [comment]
Hmnn that's curious, I have transparency in some of my watermarks and it works ok.

Can you attach one of the watermarks you are trying so that I can test to see what's wrong?

**Comment by fkick** [comment]
Ah, this looks to have been an issue on my end with creating the PNG files. Sorry!
