### ISSUE TITLE
Suggestion: Mass Add Flex between shows

### ISSUE THREAD

**Issue by deanochips** [vexorian/dizquetv#388]
Instead of having to add a single add break individually after every show, i would be amazing to have one button that would allow you to select a default flex length time and add a flex break between every episode on a channel, i currently have 81 channels and managing individual flex breaks on that many channels is unmanageable

this change combined with you already existing flex lists would make this almost trivial to manage

**Comment by vexorian** [comment]
There are the "pad times" and "add breaks" tools that will add breaks to the whole schedule. Pad times add breaks in a way such that the start times of the programs are always 0:00 or 0:30 (or similar rules). And add breaks adds flex time between episodes when they periods without flex exceed some time.
