### ISSUE TITLE
MKV video files cause channel to restart

### ISSUE THREAD

**Issue by TopHatMan** [vexorian/dizquetv#390]
On inspection I have few channels one is All Simpsons and one is NCIS.

Now when you channel surf the show is restarted always.

What kind of info do you need to look into this and I will update this issue post.

From my first observation those channels did not have Flex. But now on further inspection it seems to be fact of MKV format. 

other formats seem to play way its supposed to work.

I also want ability to burn in srt subtitles. Plex uses format of ep name .locale.srt

so title.en.srt as example.

I also want to switch audio channels looking at the source code since other day. I will do my best to help out and investigate MKV issue.

**Comment by vexorian** [comment]
Make sure normalization is enabled in ffmpeg tab. If it is not supported to switch video formats when normalization is not enabled.

**Comment by TopHatMan** [comment]
![image](https://user-images.githubusercontent.com/36683809/135858453-25d76717-20f5-43d9-82a1-df6e22401cc9.png)
![image](https://user-images.githubusercontent.com/36683809/135858496-cb43e9d8-4a65-4b80-8b17-d428e267fb17.png)


That is enabled

**Comment by TopHatMan** [comment]
https://github.com/vexorian/dizquetv/blob/main/src/plexTranscoder.js

I was messing with the code her to investigate something on my end. But it was my mistake.

changing line 80 to false causes the issues I faced with MKV.

I was having plex transcoder issues crapping out. I wanted to always force plex to transcode.

My 2 main issues are subtitle srt file loading shows and forcing audio channel based on language. 

Gonna close this because my hunch was right I caused the error.

**Comment by TopHatMan** [comment]
This is interesting , the simpsons channel is now fixed , but star trek channel is same. Both are MKV.

**Comment by TopHatMan** [comment]
`[tls @ 000002a6ed1f5540] Error in the pull function.4:37.99 bitrate=5931.3kbits/s speed=   1x
[matroska,webm @ 000002a6ecef0780] Read error
[tls @ 000002a6ed1f5540] The specified session has been invalidated for some reason.
    Last message repeated 1 times
https://192-168-1-97.x.plex.direct:32400/library/parts/19385/-92442600/file.mkv?X-Plex-Token=WobfPRgxCN2osadCNCVZ: I/O error
    Last message repeated 15 times
https://192-168-1-97.x.plex.direct:32400/library/parts/19385/-92442600/file.mkv?X-Plex-Token=WobfPRgxCN2osadCNCVZ: I/O error
    Last message repeated 1 times`

**Comment by vexorian** [comment]
I saw that happen when Plex shuts down the transcode session for whatever reason. usually it's concurrent transcode limit.

**Comment by TopHatMan** [comment]
Ok , I will investigate but its odd how some shows still do the whole restart ep thing.

**Comment by TopHatMan** [comment]
`  if (this.settings.streamPath === 'direct' || this.settings.forceDirectPlay) {
            if (this.settings.enableSubtitles) {
                this.log("Direct play is forced, so subtitles are forcibly disabled.");
                this.settings.enableSubtitles = false;
            }
            stream = {directPlay: true}
        } else {`

this is why I fiddled with the direct play , I wanted the program to burn in srt subs.

**Comment by TopHatMan** [comment]
`  let bFoundJP = false;
                streams.forEach(function (stream) {
                    // Audio. Only look at stream being used
                    console.log(stream["language"]);
                    console.log(stream["languageTag"]);
                    //if dual audio and 1st audio is english
                    console.log(stream["languageTag"] === 'ja')
                    if (stream["languageTag"] === 'ja'){
                        index = stream.index; //solved
                        console.log('found');
                        bFoundJP = true;
                    }
                    if ((stream["streamType"] == "2") && (stream["selected"] == "1") && (bFoundJP !== true)) {
                        index = stream.index
                    }
                });`

dual audio fix for common Japanese animes
