### ISSUE TITLE
[Semi Done] Prefer audio locale over default locale

### ISSUE THREAD

**Issue by TopHatMan** [vexorian/dizquetv#391]
This alteration takes in language code in iso2 so 'en' 'ja'

`async getAudioIndex(preferLocale = '') {
    let index = 'a';
    console.log('uri: ', `${this.server.uri}${this.key}?X-Plex-Token=${this.server.accessToken}`);
    await axios.get(`${this.server.uri}${this.key}?X-Plex-Token=${this.server.accessToken}`, {
      headers: {
        Accept: 'application/json'
      }
    }).then(res => {
      try {
        console.log('PLEX audio data RES \n', res.data);
        let streams = res.data.MediaContainer.Metadata[0].Media[0].Part[0].Stream;
        let bFoundLocale = false;
        streams.forEach(function (stream) {
          // Audio. Only look at stream being used
          console.log(stream["languageTag"]);

          if (preferLocale !== '') {
            //if dual audio and 1st audio is english
            console.log(stream["languageTag"] === preferLocale);

            if (stream["languageTag"] === preferLocale) {
              index = stream.index; //solved

              console.log('found');
              bFoundLocale = true;
            }
          }

          if (stream["streamType"] == "2" && stream["selected"] == "1" && bFoundLocale !== true) {
            index = stream.index;
          }
        });
      } catch (e) {
        console.error("Error at get media info:" + e);
      }
    }).catch(err => {
      console.error("Error getting audio index", err);
    });
    this.log(`Found audio index: ${index}`);
    return index;
  }`

It takes in one var but assumes blank for ignoring. Then if it founds JA it will flag it and stop looking.

already tested 

I am looking at grabbing streamType === '3' for subtitles and burn ins.

This was issue for some of my anime is dual audio and I dont want to hear the dub.

I did a double test now and it works. Now of course you need to add this to the angular UI.

But I am only really versed in React.

I never really did any git pull requests ever. I know this is not best way to send in help.

**Comment by vexorian** [comment]
Hmnn it's supposed to pick the audio and subtitle tracks selected for the Plex user in Plex UI. I have a lot of anime in my channels and this works for me, it just happens that with some shows I have to manually set the subtitle/audio tracks in plex , but there's a script for that supposedly.

Where the tracks selected correctly in plex and you were still having the issue without this change?

**Comment by TopHatMan** [comment]
This is rare edge case where plex is wrong or does not select what i want. now subtitles do not work for me at all. I see the meta data streamType 3 is sub titles. its a ass subtitle.

**Comment by TopHatMan** [comment]
> Hmnn it's supposed to pick the audio and subtitle tracks selected for the Plex user in Plex UI. I have a lot of anime in my channels and this works for me, it just happens that with some shows I have to manually set the subtitle/audio tracks in plex , but there's a script for that supposedly.
> 
> Were the tracks selected correctly in plex and you were still having the issue without this change?

Do you know how to select certain subs , like i got anime like Gundam and it has 2 subs sub 1 is not really the sub. Sub 2 is so I would need to select the 2nd sub.

**Comment by vexorian** [comment]
Plex's automatic selection of subtitles or audio is often wrong. But nothing stops you from picking them manually. Once you pick the correct subtitle and audio track manually in plex, dizquetv will play it.

**Comment by TopHatMan** [comment]
Can you do this for every series or per episode. But I can make it default is what your saying for per series.

**Comment by TopHatMan** [comment]
Yeah I get that , but the code I wrote will only affect dual audio anime. As well as it can be set to ignore completely.  For me example this one anime has 2 audio tracks and 1 subtitle track. yet it does not even play the subtitle?
