### ISSUE TITLE
Request: ability to add Flex media via folder

### ISSUE THREAD

**Issue by Arlutaka** [vexorian/dizquetv#45]
Issue: I have Flex media stored in a Plex Library of 'Other Videos' type, in a separate folder, named ETC,

I've found that when you go to add Flex media from an 'Other Videos' Plex library, no matter how the videos are sorted in subfolders, it shows all videos from that library the dropdown, ignoring the subfolder sorting. I have multiple types of Flex media (kids, horror, commercials, etc) organized into subfolders within this Plex Library so it's difficult to sort through. 

I'd like the ability to select a folder inside my 'Other Videos' library, and add all of those videos as Flex media. This is similar to how when adding TV Shows to a channel, you can add all episodes of all seasons of 1 series, by clicking the  + on the Series (or season) title.

Let me know if this is possible, or if this is a limitation of Plex libraries
Thanks!

**Comment by vexorian** [comment]
I never noticed this because I use collections in my "Other Videos" library. I find it works better than folders, because you can have the same video in multiple libraries.

Still maybe it's a good idea, for "Other Videos" libraries specifically. A problem here is that I am not sure if Plex api even makes a differentiation between Other Videos libraries and Movie libraries.

**Comment by Arlutaka** [comment]
I sorted all my  Flex media into collections as you suggested. 
It doesn't appear to me that dizquetv recognizes collections. When adding media it only shows a Library and all media in it.
![image](https://user-images.githubusercontent.com/69775964/90352066-30bcce80-e010-11ea-83cd-7aea085e1dc9.png)

**Comment by vexorian** [comment]
Update to 0.0.62, it has collections support

**Comment by Arlutaka** [comment]
I will close this request then and sort by collections.
Thank you for all your hard work!
