### ISSUE TITLE
Set Transcode resolution on per-channel basis

### ISSUE THREAD

**Issue by Browneye3001** [vexorian/dizquetv#48]
At the moment you set a universal transcode resolution and normalisation parameters for all channels.

It would be nice to set these settings per channel so you can have different resolutions and normalisation. 

e.g. you can have a 4K channel that doesn't transcode, but normalise a bunch of different SD clips on it's own channel.

**Comment by lsultana98** [comment]
I don't know the possibility of this feature. But it would be great if possible.

**Comment by nwithan8** [comment]
Closed by per-channel FFMPEG settings in v1.2.0

**Comment by MoRBiD-MaNGLeR** [comment]
Closing per comments above.
