### ISSUE TITLE
Bad aspect ratio and sound glitches after episode change

### ISSUE THREAD

**Issue by fr500** [vexorian/dizquetv#52]
Hi

I just setup dizquetv with these settings

![imagen](https://user-images.githubusercontent.com/1721040/90457654-c06e8580-e0c1-11ea-97a2-7281dc9e132b.png)

So, I have this issue. Sometimes after an episode ends and another starts, sound glitches terribly, basically all I get is noise.
Also, after a 4:3 episode ends a 16:9 episode is stretched to 4:3 and looks horrible.

Is there any way to improve this?

**Comment by vexorian** [comment]
Enable normalization in ffmpeg tab

**Comment by fr500** [comment]
ah, alright, so I'm forced to using transcoding?
I prefer to use directplay whenever possible...

Another slightly unrelated question, when transcoding, will plex then transcode again if using this remotely honoring the remote transcoding parameters?

**Comment by vexorian** [comment]
You are not forced to use transcoding. But you are forced to choose between the three following things:
- Transcoding
- Using the same format in all the media playing in a channel
- Stream breaking when the the episode switches

It's because dizquetv has to maintain a single stream running.

**Comment by fr500** [comment]
Thank you
