### ISSUE TITLE
Can't Open Admin Panel

### ISSUE THREAD

**Issue by dekiscool** [vexorian/dizquetv#54]
Everything was going fine...and then I accidentally closed out the admin panel...where you have all the settings...create channels etc. I went to open it back up and it's not responding. It says Unable to connect. Not sure why. It's the same one I found in the instructions...and it worked before. 

Any ideas?

Thanks in advance

**Comment by MoRBiD-MaNGLeR** [comment]
Did you accidentally also close the dizqueTV executable?  It's what allows the website to work.

**Comment by dekiscool** [comment]
Yeah...feel stupid. I thought I had closed it and reopened it to refresh the guide...either I didn't reopen it or it closed itself...not sure. But it is working again. Thanks
