### ISSUE TITLE
Channel Icon Stuck

### ISSUE THREAD

**Issue by elit3ge** [vexorian/dizquetv#56]
When I was first playing around with channel icons I set one for channel 6 and all the others were the default one. I have since gone through and made channel icons and replaced all the channel icons in dizquetv, they all appear in Plex now except for the first icon that I changed has stayed the same. I have checked the XML and followed the link and it goes to the new one, seems like its stuck in plex. Is there a way to force icon refreshes?

**Comment by elit3ge** [comment]
Tried removing the DVR, restarting plex and then adding it again. Little icon comes back!

**Comment by MoRBiD-MaNGLeR** [comment]
@elit3ge It's not clear to me.  Is this resolved or still an issue?

**Comment by elit3ge** [comment]
@MoRBiD-MaNGLeR still an issue.

**Comment by nwithan8** [comment]
What player are you using? If it's a web browser, maybe try clearing your cache?
Also, have you tried stopping and restarting the Plex Media Server application?

**Comment by elit3ge** [comment]
@nwithan8 It's an AppleTV. Yes to the restart.

**Comment by elit3ge** [comment]
Resolved itself.
