### ISSUE TITLE
Get Could not tune channel. Please check your tuner or antenna 

### ISSUE THREAD

**Issue by bferrell** [vexorian/dizquetv#6]
Plex Version 1.20.0.3181
DizqueTV 0.0.60

**Comment by vexorian** [comment]
This could be caused by a lot of different issues. Usually it's ffmpeg not
being setup correctly or being the wrong version (should be 4.2.3 or
higher). Try to look at dizque's logs when this happens

**Comment by andytt11** [comment]
ffmpeg was my cause. The cmd line said it couldn't find the path but I forgot to add .exe to the end.

**Comment by bferrell** [comment]
I poked for a while and that was exactly the problem... a bad build of ffmpeg on OS X
