### ISSUE TITLE
Request: Merge IPTV data with custom channels

### ISSUE THREAD

**Issue by d8ahazard** [vexorian/dizquetv#65]
Heyoo! Me again.

I've got another request. Would it be possible to make it so that we could use IPTV data in conjunction with DizqueTV? 

For example, I've got a m3u an xmltv from tv.xyz.com. I open DizqueTV, import those files, they are added to the normal lineup in Dizque, with the option to maybe rename or renumber the channels?

**Comment by vexorian** [comment]
This sort of thing is out of dizqueTV's scope. Normally we use xTeVe to create aggregated TV line ups.  xteve is a project that can take different m3u and xmltvs from different sources (including dizquetv) and aggregate them together into a single one or a simulated HDHR https://github.com/xteve-project/xTeVe
