### ISSUE TITLE
Infinite playback loop when starting to play a video near its end

### ISSUE THREAD

**Issue by vexorian** [vexorian/dizquetv#69]
If by some chance of destiny you start playback of a vide when there are less than 10 seconds left to play it, it can enter an infinite loop. This is similar to the error that was fixed some versions ago where videos shorter than 10 seconds would loop infinitely. The fix to that issue relied on checking the length of the video, but that fix doesn't work in this situation

**Comment by vexorian** [comment]
Hmnn I am not sure if I fixed this :/

**Comment by vexorian** [comment]
I was able to reproduce this in 1.0.1, so nope. It's not fixed.

**Comment by merrychrishna** [comment]
im on the newest version for windows and im stuck in an infinite loop. how can i fix it? or did you not update the windows binary with your fix? can you do that please because i dont know how to compile it.

**Comment by vexorian** [comment]
This issue was fixed a long time ago and the windows version of 1.4.3 should have the fix. If you are experiencing infinite loops, it's something else.

- Do they happen when playing the channel using VLC?
