### ISSUE TITLE
Loop video in Flex break

### ISSUE THREAD

**Issue by kwbisch** [vexorian/dizquetv#76]
I'd like to loop a video during flex period.  Here's my use case.

I have a Christmas Channel for my wife. I'd like the movies to start at :00 and :30.  When there's no movie playing, I'd like to loop a video of a snowy scene with Christmas music behind it until it's time for the next movie to start.

I've got the clip, I just need to loop the video. Right now, the flex break plays the video once and stops.  I've tried setting the replay timer to 0 and then setting it to 1 minute (and making my video 2 minutes long), but neither of those worked.

**Comment by vexorian** [comment]
Use fall back video for this

**Comment by kwbisch** [comment]
Perfect! I can't believe I missed that!  Thank you.
