### ISSUE TITLE
Tweak Weights Empties Channel

### ISSUE THREAD

**Issue by keithdok** [vexorian/dizquetv#82]
I hadn't tried it before 0.65, but on this version when I go to Tweak Weights and change the weight of a show I've added to a channel, then click Apply, it removes all programming from the schedule for that channel and says "No Programs Are Currently Scheduled".

**Comment by vexorian** [comment]
I just tested this in 65. And the channel saves fine. It must be something specific about the channel you were trying to build. Need more information on how to reproduce the bug

**Comment by MoRBiD-MaNGLeR** [comment]
@keithdok Using Version 0.0.67, try again to reproduce the issue.  If repeatable, provide steps to reproduce.  Otherwise, let us know if it is resolved.

**Comment by vexorian** [comment]
Didn't get more reports of this for 18 days and I used tweak weights in multiple occasions. If you discover a way to make it reproduceable, please post it again in another issue with a description of the steps to reproduce it. Closing it for now.
