### ISSUE TITLE
Channel Icon in Docker

### ISSUE THREAD

**Issue by chuckkyle** [vexorian/dizquetv#83]
I hope that I have done my due diligence in trying to solve this issue.

Equipment:
Synology NAS running DSM
File Station
Docker
dizqueTV

I am trying to change the channel icons.  

First I created a folder on the volume1/appdata/dizqueTV1/images as a place to put my icon images and placed the file bond.jpg
Second I mapped the docker volume as follows:
File/folder                                            Mount Path
appdata/disqueTV1/images             /.dizquetv/images
appdata/disqueTV1                        /.dizquetv

Then in dizqueTV I used http://192.168.1.45:32778/images/bond.jpg (or some variation) each time I would either get a message that the URL was incorrect or I would get an icon picture that looks like a space holder and not the jpg

After failing at mapping.  I then used telnet and tried to copy the file directly into the container using 
docker cp bond.jpg ec1d2f2ad72f:/.dizquetv/images 

no luck doing that either.

Any suggestions on how to get images into the container?

Thanks

Chuck

**Comment by vexorian** [comment]
You have to use volumes, that's correct.

The container path for .dizquetv folder is: `/home/node/app/.dizquetv` not `/.dizquetv`

**Comment by chuckkyle** [comment]
Worked perfect.  Thanks
